### ISSUE TITLE
modals broken

### ISSUE THREAD

**Issue by ohitstom** [spicetify/cli#3090]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.41.434.g39a25e2c
Spicetify v2.36.14
Theme: Comfy / Comfy
Extensions: npvAmbience.js, toggleDJ.js, gamepad.js, spotifyBackup.js, playbarClock.js, quickQueue.js, scannables.js, sleepTimer.js, tracksToEdges.js, adblock.js, immersiveView.js, volumePercentage.js
Custom apps: lyrics-plus, new-releases, marketplace
xpui_2024-06-28_1719586782170_39a25e2
cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Runtime: Chrome
Build System: CMake
```

### 📝 Description

Updated spotify and spice at the same time, modals are still broken

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/22730962/ac26e17f-f02e-41b4-9c20-fdcbceebc5bb)

**Comment by ohitstom** [comment]
![image](https://github.com/spicetify/cli/assets/22730962/6e9ec62a-ec91-48e5-bf77-3b983259a006)
![image](https://github.com/spicetify/cli/assets/22730962/f453365f-0d7c-41f2-a161-a4e830325e0a)

**Comment by sanoojes** [comment]
am also facing same issues updated the css map and reinstalled spicetify and spotify is is fixed ?

![image](https://github.com/spicetify/cli/assets/93819264/2565d049-0855-483a-a670-afbc41c43638)

i added some custom css to fix it for now 

```css
generic-modal {
  height: 100vh;
  width: 100vw;
  position: fixed;
  display: flex;
  align-items: center;
  justify-content: center;
}

.GenericModal__overlay {
  display: flex;
  width: 100%;
  z-index: 100;
  height: 100%;
  justify-content: center;
  align-items: center;
}
```
